%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Sandipan/Desktop/Test/neff.xlsx
%    Worksheet: neff
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/28 22:05:29

%% Import the data
[~, ~, raw] = xlsread('/Users/Sandipan/Desktop/Test/neff.xlsx','neff');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Slab_width = data(:,1);
TE0 = data(:,2);
TE1= data(:,3);
TE2 = data(:,4);
TE3 = data(:,5);
TE4 = data(:,6);
TM0 = data(:,7);

%% Draw graph
fig =  figure('Color', 'w');
plot (Slab_width, TE0, '-g', 'LineWidth', 2);
hold on;
plot (Slab_width, TE1, '-b', 'LineWidth', 2);
plot (Slab_width, TE2, '-y', 'LineWidth', 2);
plot (Slab_width, TE3, '-c', 'LineWidth', 2);
plot (Slab_width, TE4, '-m', 'LineWidth', 2);
plot (Slab_width, TM0, '-r', 'LineWidth', 2);
hold off;
xlabel({'Slab Width','(in micro meter)'},'FontSize',16,'FontWeight','bold','Color','b')
ylabel({'Refractive Index'},'FontSize',16,'FontWeight','bold','Color','b')
legend ('TE0','TE1','TE2','TE3','TE4','TM0','Location','NorthEast');
axis([.7 2 1 2.7])
%% Clear temporary variables
clearvars data raw R;