%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Sandipan/Desktop/Test/Final.xlsx
%    Worksheet: mems-1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/09 15:13:45


%% Import the data
[~, ~, raw1] = xlsread('/Users/Sandipan/Desktop/Test/Final.xlsx','mems-1');
raw1 = raw1(2:end,[2,end]);

[~, ~, raw2] = xlsread('/Users/Sandipan/Desktop/Test/Final.xlsx','mems-2');
raw2 = raw2(2:end,[2,end]);

[~, ~, raw3] = xlsread('/Users/Sandipan/Desktop/Test/Final.xlsx','mems-3');
raw3 = raw3(2:end,[2,end]);

[~, ~, raw4] = xlsread('/Users/Sandipan/Desktop/Test/Final.xlsx','mems-4');
raw4 = raw4(2:end,[2,end]);

%% Create output variable
data1 = reshape([raw1{:}],size(raw1));
data2 = reshape([raw2{:}],size(raw2));
data3 = reshape([raw3{:}],size(raw3));
data4 = reshape([raw4{:}],size(raw4));

%% Allocate imported array to column variable names
w_beam1 = data1(:,1);
absreallog10rp1 = data1(:,2);

w_beam2 = data2(:,1);
absreallog10rp2 = data2(:,2);

w_beam3 = data3(:,1);
absreallog10rp3 = data3(:,2);

w_beam4 = data4(:,1);
absreallog10rp4 = data4(:,2);

%% Draw graph
%stem(w_beam,absreallog10rp,'MarkerFaceColor','g')
hold on
%stem(w_beam1,absreallog10rp1,'MarkerFaceColor','r')
%stem(w_beam2,absreallog10rp2,'MarkerFaceColor','g')
stem(w_beam3,absreallog10rp3,'MarkerFaceColor','b')
stem(w_beam4,absreallog10rp4,'MarkerFaceColor','c')
hold off


%% Labels
xlabel('Rib width of MEMS waveguide \mum', 'FontSize',14,'Color','black')
ylabel_eq = '$${ log \frac{E_{x_{mode}}}{E_{y_{mode}}}}$$';
ylabel(strcat('Log ratio of E-field = ', ylabel_eq), 'FontSize',18,'FontWeight','bold','Color','black','Interpreter','latex')


%% Clear temporary variables
clearvars data raw;