%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Sandipan/Desktop/Test/Final.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/08 00:29:16

%% Import the data
[~, ~, raw] = xlsread('/Users/Sandipan/Desktop/Test/Final.xlsx','Sheet1');
raw = raw(2:end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
xvalues = data(:,1);
yvalues = data(:,2);
lambda = data(:,3);
zdata = data(:,4);

%% Draw figure
figure
stem3(xvalues, yvalues, zdata, 'Color', 'b') 

%% Clear temporary variables
clearvars data raw;