%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Sandipan/Desktop/Test/Final.xlsx
%    Worksheet: Sheet2
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/08 21:22:03

%% Import the data
[~, ~, raw] = xlsread('/Users/Sandipan/Desktop/Test/Final.xlsx','Sheet2');
raw = raw(2:end,[1:2,end]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
w_RR1 = data(:,1);
w_slab = data(:,2);
sum1 = data(:,3);

%% Draw figure Method 1
matrix = [w_RR1 w_slab sum1];
tri = delaunay(matrix(:,1),matrix(:,2));
trisurf(tri,matrix(:,1),matrix(:,2),matrix(:,3))
shading faceted

%% Draw figure Method 2
%stem3(w_RR1,w_slab,sum1,'MarkerFaceColor','g')

%% Draw min on graph
hold on
[~,i] = min(sum1(:));
h = scatter3(w_RR1(i),w_slab(i),sum1(i),'filled', 'MarkerFaceColor','red');
h.SizeData = 150;

strxmin = [' Rib_{width} = ',num2str(w_RR1(i))];
strymin = [', Slab_{width} = ',num2str(w_slab(i))];
%text(w_RR1(i),w_slab(i),strcat('Minimum at',strxmin,'\mum',strymin,'\mum'),'HorizontalAlignment','left', 'Color', 'red', 'FontSize', 12)
hold off

%% Labels
xlabel('Rib width in \mum', 'FontSize',18,'FontWeight','bold','Color','black')
ylabel('Slab width in \mum', 'FontSize',18,'FontWeight','bold','Color','black')

zlabel_eq = '$$\sum_{mode}{abs\left(log \frac{E_{x_{mode}}}{E_{y_{mode}}}\right)}$$';
zlabel(strcat('Log ratio of E-field = ', zlabel_eq), 'FontSize',22,'FontWeight','bold','Color','blue','Interpreter','latex')



%% Clear temporary variables
clearvars data raw R;