%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Sandipan/Desktop/Test/mems.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/13 18:31:06

%% Initialize variables.
filename = '/Users/Sandipan/Desktop/Test/mems.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: text (%q)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%q%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
K=100;
w_beam = dataArray{:, 1};
w_mems = dataArray{:, 2};
w_beam(:) = round(w_beam(:)*K);
w_mems(:) = round(w_mems(:)*K);

lambda = real(str2double(dataArray{:, 3}));
rp = abs(real(log10(dataArray{:, 4})));
%rp = real(dataArray{:, 4});
k = lambda>=1;
sums = accumarray( { w_beam(k), w_mems(k)}, rp(k),[],[],[],true );
[i,j,k] = find(sums);

%% Draw area chart
figure
hold on

%[i,j,k] = peaks(10000);

%surf(i,j,k);

%[X,Y] = meshgrid(0:1:50,0:1:50);

matrix = [i/K j/K k];
tri = delaunay(matrix(:,1),matrix(:,2));
trisurf(tri,matrix(:,1),matrix(:,2),matrix(:,3))
shading faceted
grid on
hold off

%%Draw 3 max on graph
hold on
N = 3;
[sortedX, sortedInds] = sort(k(:),'descend');
topN = sortedInds(1:N);
[m] = ind2sub(size(k), topN);

%[~,i] = max(w_abs_mode12(:));

h = scatter3(i(m)/K,j(m)/K,k(m),'filled', 'MarkerFaceColor','red');
h.SizeData = 100;

text(i(m)/K,j(m)/K,k(m),strcat('(',num2str(i(m)/K),',',num2str(j(m)/K),')'),'HorizontalAlignment','left', 'Color', 'red', 'FontSize', 12)
hold off

%% Labels
xlabel('MEMS Rib width in \mum', 'FontSize',18,'FontWeight','bold','Color','black')
ylabel('MEMS Base width in \mum', 'FontSize',18,'FontWeight','bold','Color','black')

zlabel_eq = '$$\sum_{mode}{abs\left(log \frac{E_{x_{mode}}}{E_{y_{mode}}}\right)}$$';
zlabel(strcat('Log ratio of E-field = ', zlabel_eq), 'FontSize',22,'FontWeight','bold','Color','black','Interpreter','latex')


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;